### ISSUE TITLE
Full version doesn't works anymore on Windows

### ISSUE THREAD

**Issue by DoubleYo** [Baptvincent/Easy-Put.io#4]
Hi, Google Chrome block external .ctx extention. The none compressed version in developper mode works fine but this is no the full version with search engine. There is a parametter to change in order to add this feature ?

**Comment by OmgImAlexis** [comment]
@DoubleYo sorry for the extremely late reply but if you drag and drop from a folder and not the download bar it actually works. I tested this with Windows 7, 8 and 8.1 and it works with all of them.

**Comment by DoubleYo** [comment]
By cloning your repo and drag and drop the `website` folder to the extension panel it works perfectly.
One more time thank you.
